{% set org = "tdegeus" %}
{% set name = "GooseEYE" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  url: https://github.com/{{ org }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 0639f355193bc80d873013058914206e494d6054a5f8224533552a7049d091e6

build:
  number: 0
  script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  skip: true  # [python_impl == 'pypy']

outputs:

  - name: {{ name|lower }}

    script: install.sh  # [unix]
    script: install.bat  # [win]

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - xtensor
      run:
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/{{ name }}  # [unix]
        - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/{{ name }}/{{ name }}Config.cmake  # [unix]
        - if exist %LIBRARY_PREFIX%\include\{{ name }}\{{ name }}.h (exit 0) else (exit 1)  # [win]
        - if exist %LIBRARY_PREFIX%\lib\cmake\{{ name }}Config.cmake (exit 0) else (exit 1)  # [win]

  - name: python-{{ name|lower }}

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - make  # [unix]
      host:
        - numpy *
        - pip
        - pybind11
        - python
        - scikit-build
        - setuptools_scm
        - xtensor
        - xtensor-python
      run:
        - python
        - numpy *

    test:
      imports:
        - {{ name }}
      commands:
        - pip check
        - python -c "import {{ name }}; {{ name }}.version()"
      requires:
        - pip

about:
  home: https://github.com/{{ org }}/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Evaluate several geometrical statistical measures on images.
  description: |
    Library to evaluate several geometrical statistical measures on (ensembles of) 'images'
    (i.e. 1-D, 2-D, or 3-D matrices).
  doc_url: https://{{ name }}.rtfd.io
  dev_url: https://github.com/{{ org }}/{{ name }}

extra:
  recipe-maintainers:
    - tdegeus
