{% set name = "gooseeye" %}
{% set version = "0.5.0" %}
{% set sha256 = "a84a0644a6ad8dfa3063dc589b54ccc4d07f2c8bac654286d03413e349382f1d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseEYE/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  run:
    - xtensor

test:
  commands:
    - test -d ${PREFIX}/include/GooseEYE  # [unix]
    - test -f ${PREFIX}/include/GooseEYE/GooseEYE.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/GooseEYE/GooseEYEConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\GooseEYE\GooseEYE.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\GooseEYEConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/GooseEYE
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: 'Evaluate several geometrical statistical measures on images.'
  description: |
    Library to evaluate several geometrical statistical measures on (ensembles of) 'images'
    (i.e. 1-D, 2-D, or 3-D matrices).
  doc_url: https://gooseeye.rtfd.io
  dev_url: https://github.com/tdegeus/GooseEYE

extra:
  recipe-maintainers:
    - tdegeus
