{% set version = "0.8.1" %}

package:
  name: gooseeye-split
  version: {{ version }}

source:
  url: https://github.com/tdegeus/GooseEYE/archive/v{{ version }}.tar.gz
  sha256: da81c06d6a27e4d7e04c5919ced07940d8561a328dd336f0759f9641597c0f03

build:
  number: 0

outputs:

  - name: gooseeye

    script: install.sh  # [unix]
    script: install.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}

    requirements:
      build:
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
      host:
        - prrng
        - xtensor
      run:
        - prrng
        - xtensor

    test:
      commands:
        - test -d ${PREFIX}/include/GooseEYE  # [unix]
        - test -f ${PREFIX}/include/GooseEYE/GooseEYE.h  # [unix]
        - test -f ${PREFIX}/lib/cmake/GooseEYE/GooseEYEConfig.cmake  # [unix]
        - if not exist %LIBRARY_PREFIX%\include\GooseEYE\GooseEYE.h exit 1  # [win]
        - if not exist %LIBRARY_PREFIX%\lib\cmake\GooseEYE\GooseEYEConfig.cmake exit 1  # [win]

  - name: python-gooseeye

    script: install_python.sh  # [unix]
    script: install_python.bat  # [win]

    build:
      script_env: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
      skip: true  # [python_impl == 'pypy']

    requirements:
      build:
        - python                              # [build_platform != target_platform]
        - cross-python_{{ target_platform }}  # [build_platform != target_platform]
        - numpy *                             # [build_platform != target_platform]
        - setuptools_scm                      # [build_platform != target_platform]
        - {{ compiler('cxx') }}
        - cmake
        - make  # [unix]
        - ninja
      host:
        - enstat >=0.9.7
        - numpy *
        - pip
        - prrng
        - pybind11
        - pybind11-abi
        - python >=3.6
        - scikit-build
        - setuptools >=45
        - setuptools_scm >=6.2
        - xtensor
        - xtensor-python
      run:
        - enstat >=0.9.7
        - numpy *
        - python

    test:
      imports:
        - GooseEYE
      commands:
        - pip check
        - python -c "import GooseEYE; assert GooseEYE.version() == '{{ version }}'"
      requires:
        - pip

about:
  home: https://github.com/tdegeus/GooseEYE
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Evaluate several geometrical statistical measures on images.
  description: |
    Library to evaluate several geometrical statistical measures on (ensembles of) 'images'
    (i.e. 1-D, 2-D, or 3-D matrices).
  doc_url: https://GooseEYE.rtfd.io
  dev_url: https://github.com/tdegeus/GooseEYE

extra:
  recipe-maintainers:
    - tdegeus
